### ISSUE TITLE
"next-error" doesn't work soon after first compilation

### ISSUE THREAD

**Issue by TatriX** [brotzeit/rustic#102]
After first `rustic-cargo-check` or similar command, `next-error` doesn't work saying something like `user-error: Moved past last error`. To make it work I either have to focus `*rustic-compilation*` or use `next-error-select-buffer`.

**Comment by brotzeit** [comment]
I just realized

```
next-error-function is a variable defined in ‘simple.el’.
Its value is ‘flycheck-next-error-function’
```

Do you use flycheck ?

**Comment by TatriX** [comment]
Yes I do.

**Comment by birkenfeld** [comment]
I encountered this problem as well and found the reason is the logic in `next-error-find-buffer`:

* if there is exactly one window in the current frame with `next-error-function` set, use it
* if `next-error-last-buffer` is valid, use it
* if the current buffer is valid, use it
* then look for any other buffer

Since flycheck sets `next-error-function`, and we assume a multi-window setup where the compilation buffer is shown together with the source buffer, the first condition is never true.

`compile.el` sets `next-error-last-buffer` to the compilation buffer, while `rustic-compilation.el` doesn't.

The solution is therefore to add `(setq next-error-last-buffer buf)` e.g. in `rustic-compilation`.

**Comment by brotzeit** [comment]
I don't know what I there again https://github.com/brotzeit/rustic/commit/8aaf46c4ac50b067165e087192ec7678d27b89c1#diff-ad919aeb418c321a330d6d44bd63b41e2f208ef0c7d7245ac5fb56f07b1395ceL224

Once more I have to say that I need somebody reviewing my PRs...

If this issue still persists please open a new issue.
