### ISSUE TITLE
Clippy lints not working

### ISSUE THREAD

**Issue by AndreaOrru** [brotzeit/rustic#112]
Clippy lints are not working for me because of:
https://github.com/rust-lang/rust-clippy/issues/2604

This is fixed by:
https://github.com/rust-lang/rust-clippy/pull/5363
But only when specifying `-Z unstable-options` with `cargo clippy`.

At the moment I'm just redefining the flycheck checker `rustic-clippy`, setting the command to:
```emacs lisp
(flycheck-define-checker rustic-clippy
  :command ("cargo" "clippy" "-Zunstable-options" "--message-format=json")
...
...
```

**Comment by brotzeit** [comment]
Thanks for the bug report! I will make the clippy command a `defcustom` and add the unstable option parameter to the default value.

**Comment by brotzeit** [comment]
And you should consider using a lsp based checker if you are using eglot or lsp-mode.

**Comment by AndreaOrru** [comment]
> And you should consider using a lsp based checker if you are using eglot or lsp-mode.

How can I do that?

**Comment by brotzeit** [comment]
Are you using eglot or lsp-mode ?

**Comment by AndreaOrru** [comment]
> Are you using eglot or lsp-mode ?

LSP mode.

**Comment by brotzeit** [comment]
I guess you are using rust-analyzer, so it should be enough to change `lsp-rust-analyzer-cargo-watch-command` to clippy. And remove the rustic checker from `flycheck-checkers` so you can see if it works with lsp.

**Comment by AndreaOrru** [comment]
Great! Maybe that should documented on the README?

**Comment by AndreaOrru** [comment]
By the way, it works with clippy, but it doesn't seem to be showing `rustc` errors.

**Comment by brotzeit** [comment]
If you got any issues with the lsp checker please open an issue at lsp-mode.

I added a note about the lsp checker in the readme, but I wasn't able to use a defcustom as argument for the checker command. The macro doesn't seem to be able to work with values that come from a variable or you simply have to do it differently, but I couldn't find any checker that uses a variable for the command.

Since most users use the lsp based checker, I simply added `-Z unstable-options` to the command as you did.
