### ISSUE TITLE
Can I share functions between multiple source blocks?

### ISSUE THREAD

**Issue by Ayush1325** [brotzeit/rustic#122]
So, I just wanted to ask if I can call a function defined in one org-babel source block to another which are defined in the same sessions. This wasn't working with ob-rust I was trying out earlier, because it didn't allow use of external crates without a main function in that block, but having main function in there meant it couldn't be called from other blocks.

Alternatively, is there a way to add tests? I think I can hack something up if there are tests, although it would be much better to be able to share functions.

**Comment by brotzeit** [comment]
No, that's not possible at the moment. I will take a look.

**Comment by brotzeit** [comment]
Is it better to have users import functions from other babel blocks with use or do we just append additional babel block contents to the file contents of a block ?

**Comment by Ayush1325** [comment]
Use might allow for more complicated setups, I think. It will kinda be like sessions in normal org babel.

**Comment by 0atman** [comment]
Coming from a jupyter notebook background, I was expecting all blocks to share the same namespace. Certainly, that's how a simple tangle/weave literate org file ends up - all blocks in the same file.

**Comment by flintforge** [comment]
You can achieve import statements from other blocks using `:noweb` 
`[[info:org#Noweb Reference Syntax]]`
Otherwise, session mode exists only when there's a running interpreter process. It's not a matter of namespace, it's about the places the LOCs actually ends and how they're read, interpreted or compiled. 
There will be no session with a _compiled program_.
Also selecting and reading org code blocks with Lisp is fairly easy: that's what most _init.org_ do, and it opens a large range of possibilities as to how organize and assemble sources.

**Comment by brotzeit** [comment]
This is now possible with `:include`. However it's only a simple concat of the blocks.

I keep this issue open since I think it makes sense to also provide a `:use` keyword that creates modules from blocks so you can import them properly.

**Comment by brotzeit** [comment]
`:use` should now also work. Would be nice if somebody could test it.

Thanks for the feedback.
