### ISSUE TITLE
Error running rustic-doc-setup on macOS

### ISSUE THREAD

**Issue by facundoolano** [brotzeit/rustic#248]
When running `rustic-doc-setup` I get the following output in the `*rustic-doc-std-conversion*` buffer:

```
Generating org files in: /Users/facundo/.local/share/emacs/rustic-doc/std
/Users/facundo/.local/bin/rustic-doc-convert.sh: line 51: -n: command not found
error: The argument '--threads <num>' requires a value but none was supplied

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```

I think the problem is with [this line](https://github.com/brotzeit/rustic/blob/07d4d9af2c169d6cce6e2117628dfa3192937fb0/rustic-doc/convert.sh#L51). 

Running in the shell:

```
~ $ cores=$(eval "$sysctl -n hw.logicalcpu")
bash: -n: command not found
~ $ cores=$(eval "sysctl -n hw.logicalcpu")
~ $ echo $cores
8
```

**Comment by samhedin** [comment]
Thanks for the report!
I created a PR to modify it. If you want to use `rustic-doc` now, you could run the setup by changing the line you highlighted and then write protect it. `rustic-doc-setup` always tries to download the files again when it's run, but if they already exist and there is an error (which there should be since it won't be able to overwrite the old file), it will default to using the existing one and everything *should* work out.

**Comment by samhedin** [comment]
Now that it's merged - does macos setup work? I don't have access to a mac so I can't test it myself.

**Comment by facundoolano** [comment]
@samhedin yes now it's working, thanks for the prompt fix!
