### ISSUE TITLE
[Question] How to delay `cargo check`?

### ISSUE THREAD

**Issue by liebkne** [brotzeit/rustic#251]
Hi, 

Whenever I press a char, I can see `cargo check` shown on modeline immediately. And as I type quick, the `cargo check (... /...)` keep showing and disappearing all the time. It seems it's a bit frequent for me. But I can't find a custom option by `customize-group` to delay this. Is there a way to delay this check? Something like `lsp-idle-delay` or `flycheck-idle-delay`? Thanks.

**Comment by brotzeit** [comment]
Sorry for the late reply. I think this is a lsp-mode issue. Unfortunately I haven't contributed to lsp-mode for some time so I'm not really up-to-date. You could either ask on gitter/discord or open an issue. But I think it's worth that we also document it in the rustic docs.

**Comment by liebkne** [comment]
@yyoncho Could you please take a look of this to check whether it's a lsp-mode issue or not?

**Comment by jenanwise** [comment]
I am also seeing this same issue. After some investigation, it looks like the issue is noise `textDocument/didChange` → `$/progress` events from `lsp-mode` to `rust-analyzer` and back (respectively). See rust-analyzer/rust-analyzer#10075. You can ignore these events in the meantime by setting `(setq lsp-progress-function 'ignore)`. There is also `(setq lsp-progress-function 'lsp-on-progress-legacy)` which uses a less-informative but less-visually-noisy indicator. I don't think there's anything `rustic` itself can do here.

**Comment by jenanwise** [comment]
Latest (master) version of rust-analyzer seems to have solved this! I'd suggest closing this issue if you can confirm @liebkne.

**Comment by liebkne** [comment]
@jenanwise That works. Thanks for letting me know this.
