### ISSUE TITLE
Auto-formatting scrolls (sets point) to beginning of buffer

### ISSUE THREAD

**Issue by legends2k** [brotzeit/rustic#269]
I've `rustic-format-trigger` set to `'on-save`.  When the point is on some line deep down the buffer, upon saving, rustic auto formats just before saving as expected.  However, as a side effect, the point is set to the beginning of the buffer i.e. scrolls to the top.  This is quite unproductive and needless when you're actively authoring code.

Here's my configuration:

``` elisp
(use-package rustic
  :custom
  ((rustic-format-trigger 'on-save)))
```

# Details

- Rustic Version: 20210805.1755 (commit `1941f52d34e7e4752e1e465e5636b21ef7ad42b9`)
- Emacs Version: 27.2
- OS: macOS 11.4

**Comment by brotzeit** [comment]
Yeah there's at least an open issue for this problem. I thought this was fixed some time ago, maybe this is a regression. Or maybe I'm wrong.

**Comment by appetrosyan** [comment]
Can confirm.

**Comment by brotzeit** [comment]
But formatting manually doesn't ?

**Comment by brotzeit** [comment]
At least with `rustic-format-file` this shouldn't happen anymore(that's the reason why I added the function).

**Comment by yagehu** [comment]
I was having the same problem. Then I realized I was running an old version of rustic. Pulling master fixed it. If you're using straight.el make sure you run `straight-pull-package` to update.

**Comment by brotzeit** [comment]
This does happen (depending on the buffer position) when using `rustic-format-buffer` so I changed the default to `rustic-format-file` some time ago.

**Comment by appetrosyan** [comment]
My findings: 
`rustic-format-buffer` can freeze emacs. It scrolls **and** if you have your fingers crossed, maybe unfreezes it. 

`rustic-format-file` doesn't scroll the buffer, but ignores the `.rustfmt.toml` in the project directory. This makes it almost completely useless. 

This suggests that the issue is not with `rustic` mode but with `lsp` itself.

**Comment by brotzeit** [comment]
> rustic-format-file doesn't scroll the buffer, but ignores the .rustfmt.toml in the project directory. This makes it almost completely useless.

I doubt that, since both commands use the same parameters. But I'll take a look.

> This suggests that the issue is not with rustic mode but with lsp itself.

You're right, it's very unlikely that rustic-format-buffer is the problem. It just formats the buffer string and replaces the old contents. Maybe that's a problem for rust-analyzer+lsp-mode, but that's also hard to believe.

I also encountered emacs freezes with emacs28 but that doesn't seem to be related to rust features. It could be some minor mode or even an issue with emacs internals.

**Comment by brotzeit** [comment]
Regarding the original issue, I added calls to `save-excursion` in combination with `save-window-excursion` to several functions including `rustic-format-buffer`. This did at least work for `rustic-cargo-build`.

If this still doesn't work, please open a new issue. If there are still other issues please also open a new issue and I'll try to fix it.
