### ISSUE TITLE
No auto-save despite setting buffer-save-without-query

### ISSUE THREAD

**Issue by legends2k** [brotzeit/rustic#270]
With the following configuration

``` elisp
(use-package rustic
  :config
  (add-hook 'rustic-mode-hook 'my/rustic-mode-hook))

(defun my/rustic-mode-hook ()
    "Rustic mode hook."
    (when buffer-file-name
      (setq-local buffer-save-without-query t)))
```

When I dirty a rustic buffer and build with `C-c C-c C-b`, the build happens with the file on disk, instead of saving the buffer to file and then building it.  What's strange is, even without setting `buffer-save-without-query`, rustic doesn't prompt to save the dirty buffer before proceeding with compilation.

I've confirmed that the buffer local variable `buffer-save-without-query` is set.

# Details

- Rustic Version: 20210805.1755 (commit `1941f52d34e7e4752e1e465e5636b21ef7ad42b9`)
- Emacs Version: 27.2
- OS: macOS 11.4

**Comment by brotzeit** [comment]
Tests are also not looking good. I have to take a look what's wrong.

**Comment by brotzeit** [comment]
I wasn't able to reproduce it. I even added your hook to the test suite. There are tests that depend on `buffer-save-without-query`, otherwise they would open a prompt and the tests wouldn't succeed.

Sorry I can't help, but it was either fixed since you opened this issue or there's a different reason. If it still doesn't work, maybe try it only with rustic required.
