### ISSUE TITLE
Saving the buffer disables hs-minor-mode

### ISSUE THREAD

**Issue by worikgh** [brotzeit/rustic#274]
I extensively use `hs-minor-mode` to fold code.  Saving the buffer cancels that mode.

I disabled the `rustic-format-on-save`

```
  ;; comment to disable rustfmt on save
  ;; (setq rustic-format-on-save t)
```
Now (after restarting emacs) the problem has gone away with `rust-rmt`

**Comment by brotzeit** [comment]
But you can reproduce it ?

**Comment by worikgh** [comment]
Responding I just checked again.

My initial comment was incorrect, sorry.

The mode is not disabled, but all the effects are undone.  That is all the blocks hidden are unhidden.

**Comment by brotzeit** [comment]
I think this is a side effect of the buffer revert. Can you do me a favor and try both `rustic-format-buffer` and `rustic-format-file` manually and tell me if there's a difference ? If not, this is a side effect we maybe can't avoid, I think. `rustic-format-buffer` just replaces the unformated code with the formatted instead of reverting the buffer.

**Comment by worikgh** [comment]
`rustic-format-file` is not a command in my setup.  Is that a misspelling?  

If I hide a block `hs-hide-block` and run `rustic-format-buffer` it does not undo the block hiding
