### ISSUE TITLE
Ensure we didn't remove tests that are not present in rust-mode

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#291]
It's possible that we've changed the tests that were once pulled from rust-mode during the last years. We removed those tests in #290, maybe there were changes in rustic that are worth restoring in rustic or rust-mode.

**Comment by brotzeit** [comment]
@tarsius it seems you've applied some changes to test files that we removed. Do you think it makes sense to merge those changes into rust-mode ?

**Comment by tarsius** [comment]
Where did I do that?

I probably won't be able to help you with this and similar decision. I don't remember such details as it has been such a long time and because I ended up not using rust (for the time being at least) I am also not particularly motivated to dig in again at this time.

But point me to the changes you are talking about and I will have a look. Who knows, maybe it rings a bell after all.

**Comment by brotzeit** [comment]
It doesn't look important, but thanks for the quick reply. I'll keep it open, maybe I'm motivated to take a look some day =)

And hopefully you get a good reason to take a look at rust again ;)

**Comment by tarsius** [comment]
If you are talking about the `tests` branch in my fork, then I know *nothing* about it. You wrote that change, I forked your repository, you deleted the branch from your repository, and I never got around to pruning old branches.

In fact I would like prune these branches now. So please take a look at all the branches in my fork and move those that you would like to keep over to your repository and then tell me that you are done with that.

**Comment by brotzeit** [comment]
> If you are talking about the tests branch in my fork, then I know nothing about it. 

I mean changes that were merged and afterwards removed.

It seems you already deleted the fork ? I can't find it under your repositories.

I only know that you were working on a transient pr. But I don't know which other feature branches you have. It would certainly be interesting to see that. And I especially would like to have the transient branch. I just noticed that @sehnsucht13 also started working on it two years ago #55

**Comment by tarsius** [comment]
> It seems you already deleted the fork ? I can't find it under your repositories.

It's at https://github.com/tarsiiformes/rustic.

> I only know that you were working on a transient pr.

I actually just started wrapping that up. Would you be interested in that?

> But I don't know which other feature branches you have.

I don't have any. Its just very old branches you authored. There's close to zero chance you would want to recover those, but because of my confusion about what test-changes you were talking about, I though I would mention them.

**Comment by tarsius** [comment]
Please checkout the improved `transient` branch. I have completed the list of changes. I have also outlined how I think this should be further improved and added a proof-of-concept implementation of a "transified" `cargo` subcommand. It should be fairly easy to take it from here, and I can help with any transient-related issues (but not with the cargo-specific ones). Do you want me to open a pull-request?

**Comment by brotzeit** [comment]
Sure, thanks.

**Comment by brotzeit** [comment]
https://github.com/rust-lang/rust-mode/issues/421
