### ISSUE TITLE
"rustic-maybe-format-before-compilation" stops compilation when succeeding

### ISSUE THREAD

**Issue by Joshuao95** [brotzeit/rustic#352]
Hi,

Maybe I'm confused, but I noticed that when I have `rustic-format-trigger` set to `on-compile` , if there are no formatting issues with my code, it actually wouldn't run when using `rustic-cargo-run`.

After some agonizing debugging (I'm no elisp-person), it seems like the issue is the `rustic-maybe-format-before-compilation` function 

```
(defun rustic-maybe-format-before-compilation ()
  (if (eq rustic-format-trigger 'on-compile)
      (let ((proc (rustic-cargo-fmt)))
        (while (eq (process-status proc) 'run)
          (sit-for 0.1))
        (and (not (zerop (process-exit-status proc)))
             (funcall rustic-compile-display-method (process-buffer proc))
             t))
    t))
```

From what I can see this returns `nil` if the exit code is 0, which is success in `cargo`.
This thusly causes the `run-hook-with-args-until-failure` to return `nil` in `rustic-compilation-start` and thus the body of the `when` never runs.

This seems like a straightforward bug to me, but I then wonder:
Did this behaviour ever work, or does no one uses this function other than me?

Or have I misinterpreted the code (very possible).

Appreciate any help!

**Comment by brotzeit** [comment]
Hey. Thanks for the bug report! This looks like it is the result of a major rewrite of last year, I have to admit I didn't take the time for a proper review. But I think I wouldn't have noticed it anyway =)

I was surprised to see this issue since we have a test for this functionality, but we only check if the formatting runs successfully and not if the compile process was started...

I'll take a look now.

**Comment by brotzeit** [comment]
Should be working again. And I extended the tests so we hopefully won't have a regression again.

**Comment by Joshuao95** [comment]
Thanks a lot @brotzeit ! Great package :)
