### ISSUE TITLE
Errors are not clickable with a workspace

### ISSUE THREAD

**Issue by Chris00** [brotzeit/rustic#370]
When `mycrate` is in a workspace, compilation (<kbd>C-c C-c C-b</kbd>) links in the error messages change from `src/lib.rs` to `mycrate/src/lib.rs` and `next-error` does not find the correct file to go to.  It would be really nice if this worked (workspaces come rather rapidly for separation of concerns — say a `*-sys` crate and a higher level one developed together).

**Comment by brotzeit** [comment]
Sounds like a regression. I'll take a the next days together with #355

**Comment by brotzeit** [comment]
I'm still working on a solution. The issue here is that cargo always returns the directory relative to the workspace, even if a command only runs for a single crate. But we set the `default-directory` to the crate root.

During error parsing a text property will be added to the line of the error which will later be used to jump to the error. I think the only solution that makes sense is to change the property(maybe also the relative path). It would also be possible to add advices for the goto-error functions but I think we shouldn't do that. We already have enough advices.

However updating the property is a similar challenge like error parsing since we can't ensure that the path is being processed in two chunks by the process filter. We probably need something like `compilation--ensure-parse` for it. Maybe we can add some kind of hotfix for now so it works at least in most cases. Or maybe somebody has a better idea.

**Comment by Chris00** [comment]
Thanks for your efforts.  I unfortunately do not have time to help you with this ATM but what about adding the change of directory in the buffer, à la `make -w` i.e. a message `rust-mode: Entering directory '/home/user/software/Rust/mycrate/'`, which Emacs detects?

**Comment by brotzeit** [comment]
I've tried something similar when I started looking at this issue, but it didn't work.

Since errors in dependencies of different crates in the workspace also have to work, we can change the path and text property in the compilation buffer. So I'm now trying to change default-directory again. It seems this only works when we temporarily set it in a let binding in the filter function.

I'm trying to add several tests so we can hopefully ensure that this works reliably.

**Comment by brotzeit** [comment]
So, tests seem to work. While I've added more test cases, I noticed that `compilation-auto-jump-to-first-error` doesn't work when the compilation process has not finished. The reason is that jumping to errors requires(as we know by now) default-directory to set to the workspace root. This gets really annoying =)

**Comment by brotzeit** [comment]
I tested everything I can think of. But I'm pretty sure I forgot something ;)
