### ISSUE TITLE
Feature Request: rust-analyzer standalone file support

### ISSUE THREAD

**Issue by ksqsf** [brotzeit/rustic#391]
I'm using the latest rustic (20220220) eglot (20220123) and rust-analyzer (master).

rust-analyzer supports standalone files since last year. [PR](https://github.com/rust-analyzer/rust-analyzer/pull/8955). [Code](https://github.com/rust-analyzer/rust-analyzer/blob/6a64d3c4df53ceac10c270de43738d8e547dfd2a/crates/project_model/src/workspace.rs#L94).

However, that doesn't seem to be working with rustic-mode. eglot still reports

```
[stderr] [ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("/private/tmp")]
[server-notification] Fri Feb 25 00:37:25 2022:
(:jsonrpc "2.0" :method "window/showMessage" :params
          (:type 1 :message "rust-analyzer failed to discover workspace"))
```

I checked `rustic-lsp.el` and `DetachedFiles` support seems to be missing. This feature would be useful for one-shot, single-file quick testing.

**Comment by ksqsf** [comment]
```elisp
(defclass eglot-rust-analyzer (eglot-lsp-server) ())
(cl-defmethod eglot-initialization-options ((server eglot-rust-analyzer))
  (if (locate-dominating-file buffer-file-name "Cargo.toml")
      eglot--{}
    (list :detachedFiles (vector (file-truename buffer-file-name)))))
(setq eglot-server-programs
      '((rustic-mode . (eglot-rust-analyzer . ("rust-analyzer")))))
```

This seems like a usable minimal PoC. But it's not very reliable when you have multiple detached files.

**Comment by brotzeit** [comment]
Usually this this kind of changes are applied to the lsp client. But I know the eglot maintainer and he wants eglot to be light weight. So we can add this to rustic. We need a `defcustom` that allows disabling this feature. If you want to give it a try, be my guest. Otherwise maybe I'll take a look and also tag the issue with "help wanted".

And I think if we disable it by default it should also be worth merging if it only supports one detached file(with a note in the readme). I guess most users will only use one file anyway ?
