### ISSUE TITLE
Documentation for thing at point

### ISSUE THREAD

**Issue by heyarne** [brotzeit/rustic#430]
Hi! I'm using rustic via doom-emacs and I'm wondering if I can bend it a bit more to my personal preferences. Please excuse me if an issue isn't the right way to ask for this:

1. In other language modes moving the cursor between a function's braces often show the type signature or some brief function documentation in the minibuffer. Rustic shows me a function's return type when moving the cursor to it, but is there some way to figure out the call signature outside of the autocomplete list?
2. Is there some command that shows the complete documentation for the current thing at point? There is already something like this when I autocomplete a function via tab, but it it only shows the documentation until I start typing. Is there some way to bring up that buffer again?

Thanks a lot for creating rustic!

**Comment by brotzeit** [comment]
1. that package is called eldoc. I'm pretty sure you can change the message, but I don't use eldoc so I don't know
2. there are several options to show the documentation, if you are using lsp-mode you can try lsp-ui for example

Since you are using doom-emacs I would suggest that you ask on their discord server or reddit as doom provides config options that make things easier for the user. The community seems to be very helpful so you probably get a ton of possible solutions when you ask ;)

If you want to use lsp-ui you can take a look at `lsp-ui-doc-show` and `lsp-ui-doc-glance`.

**Comment by heyarne** [comment]
Thank you very much for your help!

**Comment by heyarne** [comment]
Should anyone come here searching for an answer, I managed to get the type signature of the thing under the cursor via https://github.com/scturtle/dotfiles/blob/f1e087e247876dbae20d56f944a1e96ad6f31e0b/doom_emacs/.doom.d/config.el#L74-L85, which was linked to from https://github.com/emacs-lsp/lsp-mode/pull/1740.

**Comment by restfuladi** [comment]
> Should anyone come here searching for an answer, I managed to get the type signature of the thing under the cursor via https://github.com/scturtle/dotfiles/blob/f1e087e247876dbae20d56f944a1e96ad6f31e0b/doom_emacs/.doom.d/config.el#L74-L85, which was linked to from [emacs-lsp/lsp-mode#1740](https://github.com/emacs-lsp/lsp-mode/pull/1740).

I tried it and now I get this issue:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/14058796/202559037-b2030a12-61a6-4cf4-a241-5d34479bc087.png">
