### ISSUE TITLE
rustic-format-trigger seems to not work with M-x customize-variable

### ISSUE THREAD

**Issue by nikomatsakis** [brotzeit/rustic#77]
When I do `M-x customize-variable` and apply it to `rustic-format-trigger`, I get this

```
For help using this buffer, see [Easy Customization] in the [Emacs manual].

                                         [ Search ]

Operate on all settings in this buffer:
[ Revert... ] [ Apply ] [ Apply and Save ]

Hide Rustic Format Trigger: [Value Menu] %}: %v
```

I can't quite tell what's going on here but the last line looks very strange...?

**Comment by brotzeit** [comment]
Hmmm, I have to admit I never used `customize-variable`, I always add it to my init.el manually. But I will try to fix this.

**Comment by brotzeit** [comment]
I [fixed the defcustom](https://github.com/brotzeit/rustic/commit/cdbdc71b140bf7a3bf378dd587df3412a77dfc86), but I still get a weird customization buffer. When I rename `rustic-format-trigger` it works as expected. I have no idea what the problem is. Maybe somebody knows more about the customization facilities and can help me out here.

**Comment by brotzeit** [comment]
Ok, it seems to work. I had to reset the existing customized value. Please reopen the issue if it still doesn't work for you.
